### ISSUE TITLE
interpolate_pos_embed on MultiTask

### ISSUE THREAD

**Issue by Guillermogsjc** [IndicoDataSolutions/finetune#251]
Hi, it looks like this parameter from the multitask is not being properly inherited by the `input_pipeline`.

```python
from finetune import Classifier, MultiTask

MAX_LENGTH = 300
finetune_config = {'batch_size': 4, 
                  'interpolate_pos_embed': True,
                   'n_epochs' : 1, #default 3
                   'train_embeddings': False, 
                   'num_layers_trained': 3, 
                   'max_length': MAX_LENGTH
                  }
multi_model = MultiTask({"sentiment": Classifier, 
                         "tags": Classifier}, 
                        **finetune_config)
```

The previous code builds the multitask object. 

The next code works fine finetuning it:

```python
multi_model.finetune(X={"sentiment": X_train.regex_text.values,
                         "tags": X_train.regex_text.values}, 
                     Y={"sentiment": y_train.sentiment,
                         "tags": y_train.full_topic},
                     batch_size=4
                   )
```

Also, `multi_model.input_pipeline.config['interpolate_pos_embed'] = True` is verified.

But when prediction time comes:

```python
y_pred = multi_model.predict({"sentiment": X_train.regex_text.values,
                                   "tags": X_train.regex_text.values})
```

It does not work with:

```python
ValueError: Max Length cannot be greater than 300 if interpolate_pos_embed is turned off
```

I do not know if I am missing something on the setup or it is a conflict between the parameters of the distinct objects.

Thanks very much Madison for the great job! The `MultiTask` model is a fantastic tool for uneven multiobjective labeled data.

**Comment by madisonmay** [comment]
Hi @Guillermogsjc!  Sorry for the delay in response.  Did you get to the bottom of the problem?

**Comment by madisonmay** [comment]
Also, @benleetownsend is responsible for all the hard work on `MultiTask` support :)

**Comment by Guillermogsjc** [comment]
Hi, I am studying better this class just in case I did not understood well how it works, sorry before the early issue. Any way any correction by @benleetownsend would be much appreciated.

**Comment by benleetownsend** [comment]
@Guillermogsjc You're correct in identifying that there is a problem here, in fact none of the model config is currently being inherited by predict. I will work on a fix for this now. You should be fine to run the above with default max_length=512 in the meanwhile.

**Comment by Guillermogsjc** [comment]
Thanks @benleetownsend,

yes, it works with full default length.

At the same time, `.featurize` / `.transform` method on `MultiTask` throws a dimension problem also, I guess that this comes from the same reason.

Kind regards, and again, thanks.

**Comment by benleetownsend** [comment]
@Guillermogsjc We have just merged a fix for this and updated tests to cover your case. It will be bundled with another bug fix and released as 0.6.1 very shortly. Otherwise you can access it now by cloning development branch of finetune. Thanks for your very thorough bug report. 

I have included a patch for featurize as well. Its a little strange because the featurizer is actually the same, what can differ is the way the inputs are formatted. So the distinction between tasks is a little more fuzzy. Let me know if you have any thoughts on API design for this. It currently follows the same pattern as predict.

**Comment by Guillermogsjc** [comment]
@benleetownsend yes, already saw and installed  (`pip install git+git://github.com/IndicoDataSolutions/finetune.git@02fce984190b845c387143959319fcf1299f9e2f` does the work).

Still appearing the `.featurize` a tensor dimension error when

```python
multi_model.featurize({"sentiment": X_test.head().regex_text.values,
                                     "tags": X_test.head().regex_text.values})
```

independently if setting `max_length` or not. The `predict` works like a charm.

**Comment by madisonmay** [comment]
Interesting, I would have expected that commit to resolve your issue.  Could you paste the full traceback?

**Comment by benleetownsend** [comment]
@Guillermogsjc Any update?

**Comment by Guillermogsjc** [comment]
@benleetownsend just tested and featurize works fine now.

**Comment by madisonmay** [comment]
Awesome, glad to hear it :) 

Going to go ahead and close this issue then!
